export const ITEMS = [
  {
    id: 1,
    name: "DAVIDOFF ONE SLIM",
    price: 24.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1001",
  },
  {
    id: 2,
    name: "MARLBORO SILVER BLUE",
    price: 23.5,
    stock: "low",
    category: "SMOKING",
    barcode: "1002",
  },
  {
    id: 3,
    name: "MARLBORO VISTA",
    price: 23.5,
    stock: "low",
    category: "SMOKING",
    barcode: "1003",
  },
  {
    id: 4,
    name: "MARLBORO TOUCH",
    price: 19.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1004",
  },
  {
    id: 5,
    name: "SCISSORS RED SMALL",
    price: 12.7,
    stock: "normal",
    category: "OTHER",
    barcode: "1005",
  },
  {
    id: 6,
    name: "WILLS RED SMALL",
    price: 13.7,
    stock: "low",
    category: "SMOKING",
    barcode: "1006",
  },
  {
    id: 7,
    name: "DAVIDOFF GOLD",
    price: 24.5,
    stock: "low",
    category: "SMOKING",
    barcode: "1007",
  },
  {
    id: 8,
    name: "MARLBORO WHITE",
    price: 23.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1008",
  },
  {
    id: 9,
    name: "MARLBORO RED",
    price: 23.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1009",
  },
  {
    id: 10,
    name: "MARLBORO GOLD",
    price: 23.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1010",
  },
  {
    id: 11,
    name: "DAVIDOFF ONE",
    price: 23.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1011",
  },
  {
    id: 12,
    name: "DUNHILL GOLD",
    price: 16.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1012",
  },
  {
    id: 13,
    name: "WINSTON HI",
    price: 15.7,
    stock: "normal",
    category: "SMOKING",
    barcode: "1013",
  },
  {
    id: 14,
    name: "BENSON&HEDGES",
    price: 17.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1014",
  },
  {
    id: 15,
    name: "WINSTON RED",
    price: 17.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1015",
  },
  {
    id: 16,
    name: "WINSTON SILVER",
    price: 17.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1016",
  },
  {
    id: 17,
    name: "WINSTON BLUE",
    price: 17.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1017",
  },
  {
    id: 18,
    name: "MONTI CARLO BLUE",
    price: 13.7,
    stock: "normal",
    category: "SMOKING",
    barcode: "1018",
  },
  {
    id: 19,
    name: "WILLS GOLD SMALL",
    price: 13.7,
    stock: "normal",
    category: "SMOKING",
    barcode: "1019",
  },
  {
    id: 20,
    name: "PALL MALL DOUBLE CLICK",
    price: 15.7,
    stock: "normal",
    category: "SMOKING",
    barcode: "1020",
  },
  {
    id: 21,
    name: "MONTI CARLO SILVER",
    price: 13.7,
    stock: "normal",
    category: "SMOKING",
    barcode: "1021",
  },
  {
    id: 22,
    name: "DAVIDOFF EVOLVE WHITE",
    price: 16.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1022",
  },
  {
    id: 23,
    name: "WEST RED",
    price: 14.7,
    stock: "normal",
    category: "SMOKING",
    barcode: "1023",
  },
  {
    id: 24,
    name: "LUCKY STRIKE",
    price: 16.5,
    stock: "normal",
    category: "SMOKING",
    barcode: "1024",
  },
];
